### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by cycxtIT** [YunYouJun/sese-engine-ui#12]
你好开发者，请问一下sese搜索引擎自己搭建是需要搭建前端配上后端吗?还是前端就可以了？

**Comment by RimoChan** [comment]
只有前端也可以用我的后端，但是这样不是我的本意。
我的本意是装了这个色色引擎，人可以自己搜索，不依赖别人，这个别人包括谷歌当然也包括我。
你想，哪天我要是突然死了那你的前端不就没用了嘛。

**Comment by cycxtIT** [comment]
> 只有前端也可以用我的后端，但是这样不是我的本意。 我的本意是装了这个色色引擎，人可以自己搜索，不依赖别人，这个别人包括谷歌当然也包括我。 你想，哪天我要是突然死了那你的前端不就没用了嘛。

哦哦那好，对了网页标签怎么修改?在index.html修改吗？

**Comment by YunYouJun** [comment]
https://github.com/YunYouJun/sese-engine-ui/blob/13c19305324589e9a4ea5b10da2f23849ab01dc5/locales/zh-CN.yml#L22

中英文翻译在 `locales` 下。

**Comment by cycxtIT** [comment]
请问一下，如果我要把这个(如图圈起来的)去掉应该要怎么做?

![20220406_120859](https://user-images.githubusercontent.com/90236905/161890163-fbde524b-a36e-4690-9e97-e1d5a5a2c639.jpg)

**Comment by RimoChan** [comment]
云游快把LICENSE删了，阻止他这样做！

**Comment by cycxtIT** [comment]
> 云游快把LICENSE删了，阻止他这样做！

我想修改一下那个图标而已。。。

**Comment by cycxtIT** [comment]
算了不改了，反正也没差

**Comment by RimoChan** [comment]
我仔细想了以后，「莉沫-小云图」是这个项目的logo，那实际上它就是版权声明的一部分，所以把图片换掉是违反协议的吧？

**Comment by cycxtIT** [comment]
> 我仔细想了以后，「莉沫-小云图」是这个项目的logo，那实际上它就是版权声明的一部分，所以把图片换掉是违反协议的吧？

那好我不换了

**Comment by RimoChan** [comment]
嗯……我@一下云游来看看！ @YunYouJun

**Comment by cycxtIT** [comment]
> 嗯……我@一下云游来看看！ @YunYouJun

看看yunyoujun怎么说，图标应该是包括在内的(协议)如果违反的话那我不改了

**Comment by YunYouJun** [comment]
我给页脚添加了版权信息，如果可以的话希望是可以保留页脚信息，而页面部分的内容可以自由修改。
修改请全局搜索 img 标签。

**Comment by cycxtIT** [comment]
> 我给页脚添加了版权信息，如果可以的话希望是可以保留页脚信息，而页面部分的内容可以自由修改。 修改请全局搜索 img 标签。

我只要修改图标和logo而已，'关于'那里我会保留不修改,

**Comment by cycxtIT** [comment]
请问一下，我搭建的时候我加了ssl，能正常访问但是搜索不到东西，但是把ssl给关了的时候又能正常访问了，请问一下开发者，要怎么做加上ssl也能正常搜索啊? (虽然demo没有配置ssl

**Comment by cycxtIT** [comment]
> 请问一下，我搭建的时候我加了ssl，能正常访问但是搜索不到东西，但是把ssl给关了的时候又能正常访问了，请问一下开发者，要怎么做加上ssl也能正常搜索啊? (虽然demo没有配置ssl

**Comment by cycxtIT** [comment]
请问一下，我搭建的时候我加了ssl，能正常访问但是搜索不到东西，但是把ssl给关了的时候又能正常访问了，请问一下开发者，要怎么做加上ssl也能正常搜索啊? (虽然demo没有配置ssl

**Comment by cycxtIT** [comment]
https://github.com/YunYouJun/sese-engine-ui/blob/9c4a683260bc311b4cac94258e2c32f8be995d75/src/pages/search.vue#L101

 是不是修改这个?(搜索栏左上角的那个

![20220406_120859](https://user-images.githubusercontent.com/90236905/161985863-41c1bef7-d0c5-43cf-b2a6-fc10026790ab.jpg)

**Comment by YunYouJun** [comment]
嗯
