### ISSUE TITLE
前端莉沫酱和莉沫酱的图片不见了

### ISSUE THREAD

**Issue by mengguyi** [YunYouJun/sese-engine-ui#20]
**Describe the bug/issue**

https://upyun.yunyoujun.cn/images/sese-rimo-and-xiao-yun.png 无法访问，在墙内显示已拒绝连接，墙外提示SSL_ERROR_BAD_CERT_DOMAIN

所以现在前端是这样
![图片](https://user-images.githubusercontent.com/73788063/198829262-963366a6-6acf-435c-9372-56ffad62099c.png)

**Comment by RimoChan** [comment]
因为云游的CDN被打啦2333
@YunYouJun 话说我们有预期恢复时间吗？

**Comment by RimoChan** [comment]
还有这个图片是叫莉沫酱和小云啊……

**Comment by mengguyi** [comment]
> 因为云游的CDN被打啦2333 @YunYouJun 话说我们有预期恢复时间吗？

要不考虑把图片放ghpage，压缩成webp或AVIF

**Comment by YunYouJun** [comment]
CDN 被打了，现在迁移到 cloudflare 了，不过我打算之后直接放到仓库里吧！

**Comment by YunYouJun** [comment]
修好了。https://github.com/YunYouJun/sese-engine-ui/commit/d8f1a480f8e4aa1d3bef34814041c5ffa6752a11
