### ISSUE TITLE
搜索引擎不能添加到Chrome手机版

### ISSUE THREAD

**Issue by jinmo8** [YunYouJun/sese-engine-ui#22]
例如f搜：https://fsoufsou.com/
f搜索在搜索一次之后在手机的搜索引擎设置里面就有f搜，就是能不能优化一下让sese搜索也可以
![Screenshot_2022-11-24-13-16-55-551_com android chrome](https://user-images.githubusercontent.com/79193800/203700322-6eab54b6-6198-4b7d-a7b6-1f9e238e1359.jpg)

**Comment by YunYouJun** [comment]
<img width="360" alt="image" src="https://user-images.githubusercontent.com/25154432/203846843-238050c1-bf4a-4176-9f06-675659501038.png">

理论上现在应该也是可以的……
不大清楚手机自动生成的策略是什么。

**Comment by YunYouJun** [comment]
我知道了，看起来是这个 https://www.opensearch.org/

**Comment by YunYouJun** [comment]
Fixed. https://github.com/YunYouJun/sese-engine-ui/commit/3ba9dc0927b304db7eae6d9af63cab86165cb1d1
